
version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # Set the DATABASE_URL based on the selected db_type
      
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/mydatabase
      
    depends_on:
      
      - db
      
    # Command to run database migrations/table creation on startup (optional, but good practice)
    # This assumes create_db_and_tables() is idempotent
    command: ["/bin/bash", "-c", "python -c 'from backend.database import create_db_and_tables; create_db_and_tables()' && uvicorn backend.main:app --host 0.0.0.0 --port 8000"]

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      VITE_APP_BACKEND_API_URL: http://web:8000 # Reference the backend service by its name 'web'
    depends_on:
      - web
    volumes:
      - ./frontend:/app # Mount frontend directory for development (optional for production)

  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  

volumes:
  
  postgres_data:
  